name: "Validate PR"

on: pull_request

jobs:
  valdiate_pr_title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            docs
            refactor
            test
            ci
            chore
            revert
          requireScope: false
  validate_changelog_description:
    name: Validate Changelog Description
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: "Check for TODO statement"
        run: |
          if [ $(grep "TODO: Someone should write a nice description for this CHANGELOG" **/*.md | wc -l) != 0 ]; then exit 1; fi
  validate_spelling:
    name: Validate Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Check Spelling
        uses: streetsidesoftware/cspell-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: "**"
          config: .vscode/cspell.json
          incremental_files_only: false
          verbose: true
