name: "Validate PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  valdiate_pr_title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            docs
            refactor
            test
            ci
            chore
            revert
          requireScope: false
  validate_spelling:
    name: Validate Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Check Spelling
        uses: streetsidesoftware/cspell-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: "**/*.{md}"
          config: .vscode/cspell.json
          incremental_files_only: false
          verbose: true
